"""
This type stub file was generated by pyright.
"""

from CoreBluetooth import CBDescriptor
from bleak.backends.descriptor import BleakGATTDescriptor

"""
Interface class for the Bleak r"""
class BleakGATTDescriptorCoreBluetooth(BleakGATTDescriptor):
    """GATT Descriptor implementation f"""
    def __init__(self, obj: CBDescriptor, characteristic_uuid: str, characteristic_handle: int) -> None:
        ...
    
    @property
    def characteristic_handle(self) -> int:
        """handle for the characteristic th"""
        ...
    
    @property
    def characteristic_uuid(self) -> str:
        """UUID for the characteristic that"""
        ...
    
    @property
    def uuid(self) -> str:
        """UUID for this descriptor"""
        ...
    
    @property
    def handle(self) -> int:
        """Integer handle for this descript"""
        ...
    


