"""
This type stub file was generated by pyright.
"""

from bleak.backends.device import BLEDevice

class BLEDeviceCoreBluetooth(BLEDevice):
    """
    A CoreBlutooth class repres"""
    def __init__(self, *args, **kwargs) -> None:
        ...
    


