"""
This type stub file was generated by pyright.
"""

from typing import List
from bleak.backends.device import BLEDevice
from bleak.backends.scanner import BaseBleakScanner

logger = ...
_here = ...
class BleakScannerCoreBluetooth(BaseBleakScanner):
    """The native macOS Bleak BLE Scann"""
    def __init__(self, **kwargs) -> None:
        ...
    
    async def start(self): # -> None:
        ...
    
    async def stop(self): # -> None:
        ...
    
    def set_scanning_filter(self, **kwargs):
        """Set scanning filter for the scan"""
        ...
    
    @property
    def discovered_devices(self) -> List[BLEDevice]:
        ...
    
    @property
    def is_scanning(self): # -> None:
        ...
    


