"""
This type stub file was generated by pyright.
"""

from typing import List
from CoreBluetooth import CBService
from bleak.backends.corebluetooth.characteristic import BleakGATTCharacteristicCoreBluetooth
from bleak.backends.service import BleakGATTService

class BleakGATTServiceCoreBluetooth(BleakGATTService):
    """GATT Characteristic implementati"""
    def __init__(self, obj: CBService) -> None:
        ...
    
    @property
    def handle(self) -> int:
        """The integer handle of this servi"""
        ...
    
    @property
    def uuid(self) -> str:
        """UUID for this service."""
        ...
    
    @property
    def characteristics(self) -> List[BleakGATTCharacteristicCoreBluetooth]:
        """List of characteristics for this"""
        ...
    
    def add_characteristic(self, characteristic: BleakGATTCharacteristicCoreBluetooth): # -> None:
        """Add a :py:class:`~BleakGATTChara"""
        ...
    


