"""
This type stub file was generated by pyright.
"""

import os
from kivy.input.motionevent import MotionEvent
from kivy.input.provider import MotionEventProvider

'''
Native support for Multitouch d'''
__all__ = ('MTDMotionEventProvider', 'MTDMotionEvent')
class MTDMotionEvent(MotionEvent):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def depack(self, args): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


if 'KIVY_DOC' in os.environ:
    MTDMotionEventProvider = ...
else:
    class MTDMotionEventProvider(MotionEventProvider):
        options = ...
        def __init__(self, device, args) -> None:
            ...
        
        def start(self): # -> None:
            ...
        
        def update(self, dispatch_fn): # -> None:
            ...
        
    
    
