"""
This type stub file was generated by pyright.
"""

from kivy.input.provider import MotionEventProvider
from kivy.input.motionevent import MotionEvent

'''
TUIO Input Provider
==========='''
__all__ = ('TuioMotionEventProvider', 'Tuio2dCurMotionEvent', 'Tuio2dObjMotionEvent')
class TuioMotionEventProvider(MotionEventProvider):
    '''The TUIO provider listens to a s'''
    __handlers__ = ...
    def __init__(self, device, args) -> None:
        ...
    
    @staticmethod
    def register(oscpath, classname): # -> None:
        '''Register a new path to handle in'''
        ...
    
    @staticmethod
    def unregister(oscpath, classname): # -> None:
        '''Unregister a path to stop handli'''
        ...
    
    @staticmethod
    def create(oscpath, **kwargs):
        '''Create a touch event from a TUIO'''
        ...
    
    def start(self): # -> None:
        '''Start the TUIO provider'''
        ...
    
    def stop(self): # -> None:
        '''Stop the TUIO provider'''
        ...
    
    def update(self, dispatch_fn): # -> None:
        '''Update the TUIO provider (pop ev'''
        ...
    


class TuioMotionEvent(MotionEvent):
    '''Abstraction for TUIO touches/fid'''
    __attrs__ = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    angle = ...
    mot_accel = ...
    rot_accel = ...
    xmot = ...
    ymot = ...
    zmot = ...


class Tuio2dCurMotionEvent(TuioMotionEvent):
    '''A 2dCur TUIO touch.'''
    def depack(self, args): # -> None:
        ...
    


class Tuio2dObjMotionEvent(TuioMotionEvent):
    '''A 2dObj TUIO object.
    '''
    def depack(self, args): # -> None:
        ...
    


class Tuio2dBlbMotionEvent(TuioMotionEvent):
    '''A 2dBlb TUIO object.
    # FIXME'''
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def depack(self, args): # -> None:
        ...
    


