"""
This type stub file was generated by pyright.
"""

import os
from kivy.input.motionevent import MotionEvent
from kivy.input.provider import MotionEventProvider

'''
Support for WM_PEN messages (Wi'''
__all__ = ('WM_PenProvider', 'WM_Pen')
class WM_Pen(MotionEvent):
    '''MotionEvent representing the WM_'''
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def depack(self, args): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


if 'KIVY_DOC' in os.environ:
    WM_PenProvider = ...
else:
    win_rect = ...
    class WM_PenProvider(MotionEventProvider):
        def start(self): # -> None:
            ...
        
        def update(self, dispatch_fn): # -> None:
            ...
        
        def stop(self): # -> None:
            ...
        
    
    
