"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class BleakError(Exception):
    """Base Exception for bleak."""
    ...


class BleakDBusError(BleakError):
    """Specialized exception type for D"""
    def __init__(self, dbus_error: str, error_body: list[Any]) -> None:
        """
        Args:
            dbus_"""
        ...
    
    @property
    def dbus_error(self) -> str:
        """Gets the D-Bus error name, e.g. """
        ...
    
    @property
    def dbus_error_details(self) -> Optional[str]:
        """Gets the optional D-Bus error de"""
        ...
    
    def __str__(self) -> str:
        ...
    


CONTROLLER_ERROR_CODES = ...
PROTOCOL_ERROR_CODES = ...
