"""
This type stub file was generated by pyright.
"""

from typing import Dict

uuid16_dict = ...
uuid128_dict = ...
def uuidstr_to_str(uuid_): # -> str:
    ...

def register_uuids(uuids_to_descriptions: Dict[str, str]) -> None:
    """Add or modify the mapping of 128"""
    ...

