"""
This type stub file was generated by pyright.
"""

import threading

class ThreadWithLoggedException(threading.Thread):
    """
    Similar to Thread but will """
    DIVIDER = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def run(self): # -> None:
        ...
    


class WebsocketServerThread(ThreadWithLoggedException):
    """Dummy wrapper to make debug mess"""
    ...


