"""
This type stub file was generated by pyright.
"""

import os
from kivy.input.postproc.doubletap import InputPostprocDoubleTap
from kivy.input.postproc.tripletap import InputPostprocTripleTap
from kivy.input.postproc.ignorelist import InputPostprocIgnoreList
from kivy.input.postproc.retaintouch import InputPostprocRetainTouch
from kivy.input.postproc.dejitter import InputPostprocDejitter
from kivy.input.postproc.calibration import InputPostprocCalibration

'''
Input Postprocessing
=========='''
__all__ = ('kivy_postproc_modules', )
kivy_postproc_modules = ...
if 'KIVY_DOC' not in os.environ:
    ...
