"""
This type stub file was generated by pyright.
"""

'''
Calibration
===========

.. ver'''
__all__ = ('InputPostprocCalibration', )
class InputPostprocCalibration:
    '''Recalibrate the inputs.

    The'''
    def __init__(self) -> None:
        ...
    
    def process(self, events):
        ...
    
    def auto_calibrate(self, sx, sy, size): # -> tuple[Unknown, Unknown]:
        ...
    


