"""
This type stub file was generated by pyright.
"""

'''
Dejitter
========

Prevent blob'''
__all__ = ('InputPostprocDejitter', )
class InputPostprocDejitter:
    '''
    Get rid of jitterish BLOBs.'''
    def __init__(self) -> None:
        ...
    
    def taxicab_distance(self, p, q):
        ...
    
    def process(self, events): # -> list[Unknown]:
        ...
    


