"""
This type stub file was generated by pyright.
"""

'''
Double Tap
==========

Search t'''
__all__ = ('InputPostprocDoubleTap', )
class InputPostprocDoubleTap:
    '''
    InputPostProcDoubleTap is a'''
    def __init__(self) -> None:
        ...
    
    def find_double_tap(self, ref): # -> None:
        '''Find a double tap touch within s'''
        ...
    
    def process(self, events):
        ...
    


