"""
This type stub file was generated by pyright.
"""

'''
Ignore list
===========

Ignore'''
__all__ = ('InputPostprocIgnoreList', )
class InputPostprocIgnoreList:
    '''
    InputPostprocIgnoreList is '''
    def __init__(self) -> None:
        ...
    
    def collide_ignore(self, touch): # -> Literal[True] | None:
        ...
    
    def process(self, events): # -> list[tuple[Unknown, Unknown]]:
        ...
    


