"""
This type stub file was generated by pyright.
"""

'''
Retain Touch
============

Reus'''
__all__ = ('InputPostprocRetainTouch', )
class InputPostprocRetainTouch:
    '''
    InputPostprocRetainTouch is'''
    def __init__(self) -> None:
        ...
    
    def process(self, events):
        ...
    


