"""
This type stub file was generated by pyright.
"""

'''
Triple Tap
==========

.. versi'''
__all__ = ('InputPostprocTripleTap', )
class InputPostprocTripleTap:
    '''
    InputPostProcTripleTap is a'''
    def __init__(self) -> None:
        ...
    
    def find_triple_tap(self, ref): # -> None:
        '''Find a triple tap touch within *'''
        ...
    
    def process(self, events):
        ...
    


