"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any

"""
Interface class for the Bleak r"""
_descriptor_descriptions = ...
class BleakGATTDescriptor(abc.ABC):
    """Interface for the Bleak represen"""
    def __init__(self, obj: Any) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    @abc.abstractmethod
    def characteristic_uuid(self) -> str:
        """UUID for the characteristic that"""
        ...
    
    @property
    @abc.abstractmethod
    def characteristic_handle(self) -> int:
        """handle for the characteristic th"""
        ...
    
    @property
    @abc.abstractmethod
    def uuid(self) -> str:
        """UUID for this descriptor"""
        ...
    
    @property
    @abc.abstractmethod
    def handle(self) -> int:
        """Integer handle for this descript"""
        ...
    
    @property
    def description(self) -> str:
        """A text description of what this """
        ...
    


