"""
This type stub file was generated by pyright.
"""

"""
Wrapper class for Bluetooth LE """
from typing import Any


class BLEDevice:
    """A simple wrapper class represent"""
    def __init__(self, address : str, name : str, details: Any, rssi: Any, **kwargs: Any) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


