"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any, Awaitable, Callable, Dict, List, Optional, Tuple
from bleak.backends.device import BLEDevice

class AdvertisementData:
    def __init__(self, **kwargs : Any) -> None:
        """
        Keyword Args:
            local_name (str): The name of the ble device advertising
            manufacturer_data (dict): Manufacturer data from the device
            service_data (dict): Service data from the device
            service_uuids (list): UUIDs associated with the device
            platform_data (tuple): Tuple of platform specific advertisement data
        """
        # The local name of the device
        self.local_name: Optional[str];

        # Dictionary of manufacturer data in bytes
        self.manufacturer_data: Dict[int, bytes];

        # Dictionary of service data
        self.service_data: Dict[str, bytes];

        # List of UUIDs
        self.service_uuids: List[str];

        # Tuple of platform specific data
        self.platform_data: Tuple[Any]
    
    def __repr__(self) -> str:
        ...
    

AdvertisementDataCallback = Callable[[BLEDevice, AdvertisementData], Optional[Awaitable[None]]]
AdvertisementDataFilter = Callable[[BLEDevice, AdvertisementData], bool]
class BaseBleakScanner(abc.ABC):
    """
    Interface for Bleak Bluetoo"""
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    async def __aenter__(self): # -> Self@BaseBleakScanner:
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    @classmethod
    async def discover(cls, timeout=..., **kwargs) -> List[BLEDevice]:
        """Scan continuously for ``timeout`"""
        ...
    
    def register_detection_callback(self, callback: Optional[AdvertisementDataCallback]) -> None:
        """Register a callback that is call"""
        ...
    
    @abc.abstractmethod
    async def start(self) -> None:
        """Start scanning for devices"""
        ...
    
    @abc.abstractmethod
    async def stop(self) -> None:
        """Stop scanning for devices"""
        ...
    
    @abc.abstractmethod
    def set_scanning_filter(self, **kwargs):
        """Set scanning filter for the Blea"""
        ...
    
    @property
    @abc.abstractmethod
    def discovered_devices(self) -> List[BLEDevice]:
        """Gets the devices registered by t"""
        ...
    
    async def get_discovered_devices(self) -> List[BLEDevice]:
        """Gets the devices registered by t"""
        ...
    
    @classmethod
    async def find_device_by_address(cls, device_identifier: str, timeout: float = ..., **kwargs) -> Optional[BLEDevice]:
        """A convenience method for obtaini"""
        ...
    
    @classmethod
    async def find_device_by_filter(cls, filterfunc: AdvertisementDataFilter, timeout: float = ..., **kwargs) -> Optional[BLEDevice]:
        """A convenience method for obtaini"""
        ...
    


