"""
This type stub file was generated by pyright.
"""

import os
import sys
import threading
import jnius
from .env import get_java_setup
from .jnius import *
from .reflect import *
from six import with_metaclass

'''
Pyjnius
=======

Accessing Java'''
__version__ = ...
if sys.platform == 'win32' and sys.version_info >= (3, 8):
    ...
else:
    ...
HASHCODE_MAX = 2 ** 31 - 1
class PythonJavaClass_(with_metaclass(MetaJavaBase, PythonJavaClass)):
    @java_method('()I', name='hashCode')
    def hashCode(self): # -> Any:
        ...
    
    @java_method('()Ljava/lang/String;', name='hashCode')
    def hashCode_(self): # -> str:
        ...
    
    @java_method('()Ljava/lang/String;', name='toString')
    def toString(self): # -> str:
        ...
    
    @java_method('(Ljava/lang/Object;)Z', name='equals')
    def equals(self, other):
        ...
    


PythonJavaClass = PythonJavaClass_
if "ANDROID_ARGUMENT" in os.environ:
    orig_thread_run = ...
    def jnius_thread_hook(*args, **kwargs): # -> None:
        ...
    
