from typing import Any, Callable, Protocol

def java_method(javatypespec: str, **kwargs : Any) -> Callable[ [Callable[..., Any]], Callable[..., Any] ]: ...

class PythonJavaClass_(Protocol):
    def hashCode(self) -> int: ...
    def hashCode_(self) -> str: ...
    def toString(self) -> str: ...
    def equals(self, other : 'PythonJavaClass') -> bool: ...

PythonJavaClass = PythonJavaClass_

def jnius_thread_hook(*args : Any, **kwargs : Any) -> None: ...
    
