"""
This type stub file was generated by pyright.
"""

from uuid import UUID
from typing import List, Union
from bleak_winrt.windows.devices.bluetooth.genericattributeprofile import GattCharacteristicProperties
from bleak.backends.characteristic import BleakGATTCharacteristic
from bleak.backends.descriptor import BleakGATTDescriptor
from bleak.backends.winrt.descriptor import BleakGATTDescriptorWinRT

_GattCharacteristicsPropertiesMap = ...
class BleakGATTCharacteristicWinRT(BleakGATTCharacteristic):
    """GATT Characteristic implementati"""
    def __init__(self, obj: GattCharacteristicProperties) -> None:
        ...
    
    @property
    def service_uuid(self) -> str:
        """The uuid of the Service containi"""
        ...
    
    @property
    def service_handle(self) -> int:
        """The integer handle of the Servic"""
        ...
    
    @property
    def handle(self) -> int:
        """The handle of this characteristi"""
        ...
    
    @property
    def uuid(self) -> str:
        """The uuid of this characteristic"""
        ...
    
    @property
    def description(self) -> str:
        """Description for this characteris"""
        ...
    
    @property
    def properties(self) -> List[str]:
        """Properties of this characteristi"""
        ...
    
    @property
    def descriptors(self) -> List[BleakGATTDescriptorWinRT]:
        """List of descriptors for this ser"""
        ...
    
    def get_descriptor(self, specifier: Union[int, str, UUID]) -> Union[BleakGATTDescriptorWinRT, None]:
        """Get a descriptor by handle (int)"""
        ...
    
    def add_descriptor(self, descriptor: BleakGATTDescriptor): # -> None:
        """Add a :py:class:`~BleakGATTDescr"""
        ...
    


