"""
This type stub file was generated by pyright.
"""

from typing import List
from bleak_winrt.windows.devices.bluetooth.genericattributeprofile import GattDeviceService
from bleak.backends.service import BleakGATTService
from bleak.backends.winrt.characteristic import BleakGATTCharacteristicWinRT

class BleakGATTServiceWinRT(BleakGATTService):
    """GATT Characteristic implementati"""
    def __init__(self, obj: GattDeviceService) -> None:
        ...
    
    @property
    def uuid(self) -> str:
        ...
    
    @property
    def handle(self) -> int:
        ...
    
    @property
    def characteristics(self) -> List[BleakGATTCharacteristicWinRT]:
        """List of characteristics for this"""
        ...
    
    def add_characteristic(self, characteristic: BleakGATTCharacteristicWinRT): # -> None:
        """Add a :py:class:`~BleakGATTChara"""
        ...
    


