"""
This type stub file was generated by pyright.
"""

from kivy.effects.scroll import ScrollEffect

'''
Damped scroll effect
=========='''
__all__ = ('DampedScrollEffect', )
class DampedScrollEffect(ScrollEffect):
    '''DampedScrollEffect class. See th'''
    edge_damping = ...
    spring_constant = ...
    min_overscroll = ...
    round_value = ...
    def update_velocity(self, dt):
        ...
    
    def on_value(self, *args): # -> None:
        ...
    
    def on_overscroll(self, *args): # -> None:
        ...
    
    def apply_distance(self, distance): # -> None:
        ...
    


