"""
This type stub file was generated by pyright.
"""

from kivy.event import EventDispatcher

'''
Kinetic effect
==============

'''
__all__ = ('KineticEffect', )
class KineticEffect(EventDispatcher):
    '''Kinetic effect class. See module'''
    velocity = ...
    friction = ...
    value = ...
    is_manual = ...
    max_history = ...
    min_distance = ...
    min_velocity = ...
    std_dt = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def apply_distance(self, distance): # -> None:
        ...
    
    def start(self, val, t=...): # -> None:
        '''Start the movement.

        :Pa'''
        ...
    
    def update(self, val, t=...): # -> None:
        '''Update the movement.

        Se'''
        ...
    
    def stop(self, val, t=...): # -> None:
        '''Stop the movement.

        See '''
        ...
    
    def cancel(self): # -> None:
        '''Cancel a movement. This can be u'''
        ...
    
    def update_velocity(self, dt): # -> None:
        '''(internal) Update the velocity a'''
        ...
    


