"""
This type stub file was generated by pyright.
"""

from uuid import UUID
from typing import List, Union
from bleak.backends.characteristic import BleakGATTCharacteristic
from bleak.backends.descriptor import BleakGATTDescriptor

class BleakGATTCharacteristicP4Android(BleakGATTCharacteristic):
    """GATT Characteristic implementati"""
    def __init__(self, java, service_uuid: str, service_handle: int) -> None:
        ...
    
    @property
    def service_uuid(self) -> str:
        """The uuid of the Service containi"""
        ...
    
    @property
    def service_handle(self) -> int:
        """The integer handle of the Servic"""
        ...
    
    @property
    def handle(self) -> int:
        """The handle of this characteristi"""
        ...
    
    @property
    def uuid(self) -> str:
        """The uuid of this characteristic"""
        ...
    
    @property
    def properties(self) -> List:
        """Properties of this characteristi"""
        ...
    
    @property
    def descriptors(self) -> List:
        """List of descriptors for this ser"""
        ...
    
    def get_descriptor(self, specifier: Union[str, UUID]) -> Union[BleakGATTDescriptor, None]:
        """Get a descriptor by UUID (str or"""
        ...
    
    def add_descriptor(self, descriptor: BleakGATTDescriptor): # -> None:
        """Add a :py:class:`~BleakGATTDescr"""
        ...
    
    @property
    def notification_descriptor(self) -> BleakGATTDescriptor:
        """The notification descriptor.  Mo"""
        ...
    


