"""
This type stub file was generated by pyright.
"""

from typing import List
from bleak.backends.scanner import BaseBleakScanner
from bleak.backends.device import BLEDevice
from jnius import java_method
from . import utils

logger = ...
class BleakScannerP4Android(BaseBleakScanner):
    """
    The python-for-android Blea"""
    __scanner = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    async def start(self): # -> None:
        ...
    
    async def stop(self): # -> None:
        ...
    
    def set_scanning_filter(self, **kwargs):
        ...
    
    @property
    def discovered_devices(self) -> List[BLEDevice]:
        ...
    


class _PythonScanCallback(utils.AsyncJavaCallbacks):
    __javainterfaces__ = ...
    def __init__(self, scanner, loop) -> None:
        ...
    
    def result_state(self, status_str, name, *data): # -> None:
        ...
    
    @java_method("(I)V")
    def onScanFailed(self, errorCode): # -> None:
        ...
    
    @java_method("(Landroid/bluetooth/le/ScanResul")
    def onScanResult(self, result): # -> None:
        ...
    


