"""
This type stub file was generated by pyright.
"""

from typing import List
from bleak.backends.service import BleakGATTService
from bleak.backends.p4android.characteristic import BleakGATTCharacteristicP4Android

class BleakGATTServiceP4Android(BleakGATTService):
    """GATT Service implementation for """
    def __init__(self, java) -> None:
        ...
    
    @property
    def uuid(self) -> str:
        """The UUID to this service"""
        ...
    
    @property
    def handle(self) -> int:
        """A unique identifier for this ser"""
        ...
    
    @property
    def characteristics(self) -> List[BleakGATTCharacteristicP4Android]:
        """List of characteristics for this"""
        ...
    
    def add_characteristic(self, characteristic: BleakGATTCharacteristicP4Android): # -> None:
        """Add a :py:class:`~BleakGATTChara"""
        ...
    


