"""
This type stub file was generated by pyright.
"""

from jnius import PythonJavaClass

logger = ...
class AsyncJavaCallbacks(PythonJavaClass):
    __javacontext__ = ...
    def __init__(self, loop) -> None:
        ...
    
    async def perform_and_wait(self, dispatchApi, dispatchParams, resultApi, resultExpected=..., unless_already=..., return_indicates_status=...): # -> tuple[Unbound | Unknown | Literal[True], *tuple[Unknown, ...]]:
        ...
    


