"""
This type stub file was generated by pyright.
"""

import re
import subprocess
from ...exc import BleakError

def check_bluez_version(major: int, minor: int) -> bool:
    """
    Checks the BlueZ version.

"""
    ...

