"""
This type stub file was generated by pyright.
"""

from bleak.backends.descriptor import BleakGATTDescriptor

class BleakGATTDescriptorBlueZDBus(BleakGATTDescriptor):
    """GATT Descriptor implementation f"""
    def __init__(self, obj: dict, object_path: str, characteristic_uuid: str, characteristic_handle: int) -> None:
        ...
    
    @property
    def characteristic_handle(self) -> int:
        """handle for the characteristic th"""
        ...
    
    @property
    def characteristic_uuid(self) -> str:
        """UUID for the characteristic that"""
        ...
    
    @property
    def uuid(self) -> str:
        """UUID for this descriptor"""
        ...
    
    @property
    def handle(self) -> int:
        """Integer handle for this descript"""
        ...
    
    @property
    def path(self) -> str:
        """The DBus path. Mostly needed by """
        ...
    


