"""
This type stub file was generated by pyright.
"""

from typing import List
from bleak.backends.device import BLEDevice
from bleak.backends.scanner import BaseBleakScanner

logger = ...
_ADVERTISING_DATA_PROPERTIES = ...
class BleakScannerBlueZDBus(BaseBleakScanner):
    """The native Linux Bleak BLE Scann"""
    def __init__(self, **kwargs) -> None:
        ...
    
    async def start(self): # -> None:
        ...
    
    async def stop(self): # -> None:
        ...
    
    def set_scanning_filter(self, **kwargs): # -> None:
        """Sets OS level scanning filters f"""
        ...
    
    @property
    def discovered_devices(self) -> List[BLEDevice]:
        ...
    


