"""
This type stub file was generated by pyright.
"""

from typing import List
from bleak.backends.service import BleakGATTService
from bleak.backends.bluezdbus.characteristic import BleakGATTCharacteristicBlueZDBus

class BleakGATTServiceBlueZDBus(BleakGATTService):
    """GATT Service implementation for """
    def __init__(self, obj, path) -> None:
        ...
    
    @property
    def uuid(self) -> str:
        """The UUID to this service"""
        ...
    
    @property
    def handle(self) -> int:
        """The integer handle of this servi"""
        ...
    
    @property
    def characteristics(self) -> List[BleakGATTCharacteristicBlueZDBus]:
        """List of characteristics for this"""
        ...
    
    def add_characteristic(self, characteristic: BleakGATTCharacteristicBlueZDBus): # -> None:
        """Add a :py:class:`~BleakGATTChara"""
        ...
    
    @property
    def path(self):
        """The DBus path. Mostly needed by """
        ...
    


