"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from dbus_next.message import Message
from dbus_next.signature import Variant

_address_regex = ...
def assert_reply(reply: Message): # -> None:
    """Checks that a D-Bus message is a"""
    ...

def validate_address(address): # -> bool:
    ...

def unpack_variants(dictionary: Dict[str, Variant]) -> Dict[str, Any]:
    """Recursively unpacks all ``Varian"""
    ...

def extract_service_handle_from_path(path): # -> int:
    ...

