"""
This type stub file was generated by pyright.
"""

from kivy.uix.widget import Widget

'''
Stencil View
============

.. i'''
__all__ = ('StencilView', )
class StencilView(Widget):
    '''StencilView class. See module do'''
    ...


