"""
This type stub file was generated by pyright.
"""

import kivy.input.providers
from kivy.input.motionevent import MotionEvent
from kivy.input.postproc import kivy_postproc_modules
from kivy.input.provider import MotionEventProvider
from kivy.input.factory import MotionEventFactory

'''
Input management
=============='''
__all__ = (MotionEvent.__name__, MotionEventProvider.__name__, MotionEventFactory.__name__, 'kivy_postproc_modules')
