"""
This type stub file was generated by pyright.
"""

'''
Motion Event Factory
=========='''
__all__ = ('MotionEventFactory', )
class MotionEventFactory:
    '''MotionEvent factory is a class t'''
    __providers__ = ...
    @staticmethod
    def register(name, classname): # -> None:
        '''Register a input provider in the'''
        ...
    
    @staticmethod
    def list(): # -> dict[Unknown, Unknown]:
        '''Get a list of all available prov'''
        ...
    
    @staticmethod
    def get(name): # -> None:
        '''Get a provider class from the pr'''
        ...
    


