"""
This type stub file was generated by pyright.
"""

'''
Motion Event Provider
========='''
__all__ = ('MotionEventProvider', )
class MotionEventProvider:
    '''Base class for a provider.
    '''
    def __init__(self, device, args) -> None:
        ...
    
    def start(self): # -> None:
        '''Start the provider. This method '''
        ...
    
    def stop(self): # -> None:
        '''Stop the provider.
        '''
        ...
    
    def update(self, dispatch_fn): # -> None:
        '''Update the provider and dispatch'''
        ...
    


