"""
This type stub file was generated by pyright.
"""

'''
Motion Event Shape
============'''
__all__ = ('Shape', 'ShapeRect')
class Shape:
    '''Abstract class for all implement'''
    ...


class ShapeRect(Shape):
    '''Class for the representation of '''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    


