"""
This type stub file was generated by pyright.
"""

import socket
from typing import Any, List

from oscpy.stats import Stats


def send_message(osc_address : bytes, values : List[Any], ip_address : str, port : int, sock : socket.socket =..., safer : bool =..., encoding : str=..., encoding_errors : Any =...) -> Stats:
    ...

def send_bundle(messages, ip_address, port, timetag=..., sock=..., safer=..., encoding=..., encoding_errors=...): # -> Stats:
    """Send a bundle built from the `me"""
    ...

class OSCClient:
    """Class wrapper for the send_messa"""
    def __init__(self, address, port, sock=..., encoding=..., encoding_errors=...) -> None:
        """Create an OSCClient.

        `a"""
        ...
    
    def send_message(self, address : bytes, values : List[Any], safer : bool=...) -> Stats: ...
    
    def send_bundle(self, messages, timetag=..., safer=...): # -> Stats:
        """Wrap the module level `send_bund"""
        ...
    


