"""
This type stub file was generated by pyright.
"""

from kivy.event import EventDispatcher

'''
Code Navigation Behavior
======'''
__all__ = ('CodeNavigationBehavior', )
class CodeNavigationBehavior(EventDispatcher):
    '''Code navigation behavior. Modifi'''
    ...


