"""
This type stub file was generated by pyright.
"""

'''
Cover Behavior
==============

'''
__all__ = ('CoverBehavior', )
class CoverBehavior:
    '''The CoverBehavior `mixin <https:'''
    reference_size = ...
    cover_size = ...
    cover_pos = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def calculate_cover(self, *args): # -> None:
        ...
    


