"""
This type stub file was generated by pyright.
"""

'''
Emacs Behavior
==============

'''
__all__ = ('EmacsBehavior', )
class EmacsBehavior:
    '''
    A `mixin <https://en.wikipe'''
    key_bindings = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def keyboard_on_key_down(self, window, keycode, text, modifiers):
        ...
    
    def delete_word_right(self): # -> None:
        '''Delete text right of the cursor '''
        ...
    
    def delete_word_left(self): # -> None:
        '''Delete text left of the cursor t'''
        ...
    


