"""
This type stub file was generated by pyright.
"""

from kivy.uix.behaviors.button import ButtonBehavior

'''
ToggleButton Behavior
========='''
__all__ = ('ToggleButtonBehavior', )
class ToggleButtonBehavior(ButtonBehavior):
    '''This `mixin <https://en.wikipedi'''
    __groups = ...
    group = ...
    allow_no_selection = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def on_group(self, *largs): # -> None:
        ...
    
    @staticmethod
    def get_widgets(groupname): # -> list[Unknown]:
        '''Return a list of the widgets con'''
        ...
    


