"""
This type stub file was generated by pyright.
"""

'''
Event Manager
=============

Th'''
MODE_DEFAULT_DISPATCH = ...
MODE_FILTERED_DISPATCH = ...
MODE_DONT_DISPATCH = ...
class EventManagerBase:
    '''Abstract class with methods :met'''
    type_ids = ...
    window = ...
    def start(self): # -> None:
        '''Start the manager, bind callback'''
        ...
    
    def dispatch(self, etype, me): # -> None:
        '''Dispatch event `me` to the widge'''
        ...
    
    def stop(self): # -> None:
        '''Stop the manager, unbind from an'''
        ...
    


