"""
This type stub file was generated by pyright.
"""

from os import environ

'''
Cache manager
=============

Th'''
__all__ = ('Cache', )
class Cache:
    '''See module documentation for mor'''
    _categories = ...
    _objects = ...
    @staticmethod
    def register(category, limit=..., timeout=...): # -> None:
        '''Register a new category in the c'''
        ...
    
    @staticmethod
    def append(category, key, obj, timeout=...): # -> None:
        '''Add a new object to the cache.

'''
        ...
    
    @staticmethod
    def get(category, key, default=...): # -> None:
        '''Get a object from the cache.

  '''
        ...
    
    @staticmethod
    def get_timestamp(category, key, default=...): # -> None:
        '''Get the object timestamp in the '''
        ...
    
    @staticmethod
    def get_lastaccess(category, key, default=...): # -> None:
        '''Get the objects last access time'''
        ...
    
    @staticmethod
    def remove(category, key=...): # -> None:
        '''Purge the cache.

        :Param'''
        ...
    
    @staticmethod
    def print_usage(): # -> None:
        '''Print the cache usage to the con'''
        ...
    


if 'KIVY_DOC_INCLUDE' not in environ:
    ...
