"""
This type stub file was generated by pyright.
"""

'''
Context
=======

.. versionadde'''
__all__ = ('Context', 'ProxyContext', 'register_context', 'get_current_context')
_contexts = ...
_default_context = ...
_context_stack = ...
class ProxyContext:
    __slots__ = ...
    def __init__(self, obj) -> None:
        ...
    
    def __getattribute__(self, name): # -> Any:
        ...
    
    def __delattr__(self, name): # -> None:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __bool__(self): # -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Context(dict):
    def __init__(self, init=...) -> None:
        ...
    
    def push(self): # -> None:
        ...
    
    def pop(self): # -> None:
        ...
    


def register_context(name, cls, *args, **kwargs): # -> ProxyContext:
    '''Register a new context.
    '''
    ...

def get_current_context(): # -> Context | None:
    '''Return the current context.
    '''
    ...

_default_context = ...
