from typing import Any, Callable, Mapping

class EventDispatcher:
    def bind(self, **kwargs: Mapping[str, Callable[..., Any]]) -> None: ...
    def unbind(self, **kwargs: Mapping[str, Callable[..., Any]]) -> None: ...
    def dispatch(self, event_type: str, *args: Any, **kwargs: Any) -> None: ...
    def register_event_type(self, event_type: str) -> None: ...