"""
This type stub file was generated by pyright.
"""

'''
Factory object
==============

'''
__all__ = ('Factory', 'FactoryBase', 'FactoryException')
class FactoryException(Exception):
    ...


class FactoryBase:
    def __init__(self) -> None:
        ...
    
    @classmethod
    def create_from(cls, factory): # -> Self@FactoryBase:
        """Creates a instance of the class,"""
        ...
    
    def is_template(self, classname): # -> Literal[False]:
        '''Return True if the classname is '''
        ...
    
    def register(self, classname, cls=..., module=..., is_template=..., baseclasses=..., filename=..., warn=...): # -> None:
        '''Register a new classname referri'''
        ...
    
    def unregister(self, *classnames): # -> None:
        '''Unregisters the classnames previ'''
        ...
    
    def unregister_from_filename(self, filename): # -> None:
        '''Unregister all the factory objec'''
        ...
    
    def __getattr__(self, name): # -> Any | Type[_]:
        ...
    
    get = ...


Factory: FactoryBase = ...
if __name__ == '__main__':
    ...
