"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform

'''
Resources management
=========='''
__all__ = ('resource_find', 'resource_add_path', 'resource_remove_path')
resource_paths = ...
if platform == 'ios':
    ...
def resource_find(filename, use_cache=...):
    '''Search for a resource in the lis'''
    ...

def resource_add_path(path): # -> None:
    '''Add a custom path to search in.
'''
    ...

def resource_remove_path(path): # -> None:
    '''Remove a search path.

    .. ve'''
    ...

